DEVX-2648 Wrong config file variable name at kafkacat-example
confluentinc/examples pull request #1011
Opened 2021-07-26 17:56 UTC by RamanVerma

### Description 

https://confluentinc.atlassian.net/browse/DEVX-2648

Fix for the `kafkacat-example.sh` file. The config file specification was wrong.

### Author Validation

<-- - [x] clients/cloud Tested on a ccloud cluster -->

### Reviewer Tasks

2021-07-26 17:59 UTC, ybyzek reviewed
@RamanVerma internal tooling automatically bumps versions for new releases, in the appropriate branches.  This should not be manually done.

2021-07-26 18:16 UTC, RamanVerma commented
@ybyzek hmm, some thing went wrong with my local branch. I see that there are 14 files changed in this PR. I wanted to change just the kafkacat-example. I will correct it and remove the unwanted changes in some time. Thanks for looking into it.

2021-07-26 18:17 UTC, RamanVerma commented
Also @ybyzek, why do we have 6.2.0-post as the default branch. Just wanted to make sure that is the correct default (and not master)

2021-07-26 23:52 UTC, ybyzek requested changes
This actually won't work because the topic creation argument expects a Java-based config

```
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='<...>' password='<...>';
```

whereas kafkacat expects the librdkafka version of this:

```
sasl.username=<...>
sasl.password=<...>
```

So this PR won't work as-is.  A broader rewrite of the script and docs for the kafkacat example needs to be done.

You can do it in this PR or we can leave the jira DEVX-2648 open to address this.

2021-09-12 04:25 UTC, closed without merging

2021-09-14 13:27 UTC, ybyzek commented
This has been resolved and documentation for running this example is live at https://docs.confluent.io/platform/current/tutorials/examples/clients/docs/kcat.html