DOCS-9495 Remove incomplete list of example Replicator ACLs, instead link to Replicator and Connect docs
confluentinc/examples pull request #1015
Opened 2021-08-13 00:09 UTC by londoncalling

### Description 

https://confluentinc.atlassian.net/browse/DOCS-9495

_What behavior does this PR change, and why?_ 

No behaviour changed, only Docs. Customer reported getting stuck bringing up Replicator. The problem was they didn't have enough or the correct ACLs configured. The example here shows an incomplete list of needed ACLs, 
so it's better to point to the relevant sections where all needed ACLs are listed.

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

Signed-off-by: Victoria Bialas <vicky@confluent.io>

2021-08-13 13:23 UTC, ybyzek requested changes
@londoncalling thanks for the PR.  Requesting changes because IIUC the docs link provided isn't appropriate here because it shows ACL commands that don't work with Confluent Cloud (e.g. they show `kafka-acls` instead of `ccloud kafka acl`).

2021-08-24 23:32 UTC, londoncalling commented
@ybyzek , thanks, I never got an answer, so have marked the Jira "Needs more info". I suspect I will end up closing this PR.

2021-08-25 13:37 UTC, justinrlee commented
Hey @ybyzek @londoncalling sorry for the slow responses here.  On second thought, I don't think referencinghttps://docs.confluent.io/platform/current/multi-dc-deployments/replicator/index.html#crep-acls is that bad, because even though it lists the commands using `kafka-acls`, it also has a plain table listing the required ACLs, which could be created with `ccloud kafka acl`.  Also, the latter doc references 'cloud migration' so maybe an answer is to extend the latter doc to have both sets of commands, e.g.:

```
Commands to execute to configure the above ACLs:

kafka-acls --bootstrap-server localhost:9092 --command-config adminclient-configs.conf --add --allow-principal User:<source principal> --operation ALL --topic {__consumer_timestamps}
kafka-acls --bootstrap-server localhost:9092 --command-config adminclient-configs.conf --add --allow-principal User:<source principal> --operation ALL --topic {<group name>}

Commands to execute to configure the above ACLs in Confluent Cloud:

ccloud kafka acl create --cluster xyz --allow --service-account <service-account-id> --operation ALL --topic __consumer_timestamps
ccloud kafka acl create --cluster xyz --allow --service-account <service-account-id> --operation ALL --topic <group_name>
```

2021-08-25 19:19 UTC, londoncalling commented
@justinrlee I've done what you suggested, but not on the Migration doc (not sure which doc you are referring to) but rather in the main Replicator Security topic on this PR. I think that's the best place for it: https://github.com/confluentinc/docs-platform/pull/986

2021-08-25 23:36 UTC, londoncalling commented
@justinrlee , updates have been re-done on https://github.com/confluentinc/docs-platform/pull/986, and tested to the extent that I believe the syntax is correct. I may need to add some more lines to provide ACLs for cluster scope, because the CP commands use "ALL" and I think in some cases this implies cluster scope.

2021-08-27 19:29 UTC, ybyzek commented on ccloud/docs/includes/set-acls-destination.rst
> +documentation may be useful for other connectors.
Can we remove this part `Also...`?

2021-08-28 00:06 UTC, londoncalling commented on ccloud/docs/includes/set-acls-destination.rst
> +documentation may be useful for other connectors.
Hi @ybyzek guess, we can, I wasn't sure. I'll go ahead and remove it.

2021-08-28 12:08 UTC, ybyzek approved these changes
@londoncalling LGTM!

2021-08-30 17:16 UTC, merged