WIP: Instant kraft demo
confluentinc/examples pull request #1124
Opened 2022-09-02 01:42 UTC by addisonhuddy

Creating a single node, lightweight KRaft example that is based on the cp-all-in-one-kraft demo. Over time, this demo will evolve as the KRaft tooling improves. The main goal of the example is to show how easy it is to run Kafka in KRaft mode.

Includes 
* docker-compose file
* readme with instructions on how to run the example.
* a run script to get around some of the current ZK checks in the Confluent Kafka docker image.

2022-09-03 04:15 UTC, forlack commented on instant-kraft/README.md
> +$ git clone https://github.com/confluentinc/examples.git && cd exampls/instant-kraft
typo on cd exampls <<

2022-09-28 04:21 UTC, javabrett requested changes

2022-09-28 04:21 UTC, javabrett commented on instant-kraft/README.md
> +$ docker-compose exec broker kafka-producer-perf-test --topic zookeeper-vacation-ideas \
Commands used include both `docker compose` and `docker-compose`.  The former I think relies on later versions of Docker with either Compose included, or via a command-plugins capability.

Maybe we should stick to one.  I think our formal docs lean towards `docker-compose`.

2022-09-28 04:21 UTC, javabrett commented on instant-kraft/README.md
> +$ docker compose up
For better or worse, our examples seem to usually use `docker-compose up -d`, i.e. launch detached/daemonized, so the current shell isn't left bound to the command and tailing the logs.  Downside is that you have to `docker logs` or `docker-compose logs` to see any errors or interesting logging.

Up to you whether you want the `-d` here, but note that users might struggle with losing their shell prompt, and also unintentionally kill with CTRL-C.

2022-09-28 04:21 UTC, javabrett commented on instant-kraft/README.md
> +
Should we mention CTRL-D to exit the REPL?

2022-09-28 04:21 UTC, javabrett commented on instant-kraft/README.md
> +That's it! One container, one process, doing the the broker and controller work. No Zookeeper.
I think ZooKeeper (camel case) is standard.

2022-09-28 04:21 UTC, javabrett commented on instant-kraft/README.md
> +      '--`
Might need to be in a code block to appear proper cheesy.

2022-09-28 04:21 UTC, javabrett commented on instant-kraft/README.md
> +Explore the cluster using the new kafka metadata command line tool.
Should we refer to it inline by name?  I don't mind, just asking: `kafka-metadata-shell`

2022-09-28 04:21 UTC, javabrett commented on instant-kraft/README.md
> +That's it! One container, one process, doing the the broker and controller work. No Zookeeper.
> doing the the broker and controller work

Remove duplicate "the" and reword.  Maybe

> One container, one process performing both broker and controller/quorum roles.

2022-09-28 04:21 UTC, javabrett commented on instant-kraft/README.md
> +The key server configure to enable KRaft is the `process.roles`. Here we have the same node doing both the broker and quorum conroller work. Note that this is ok for local development, but in product
Needs rewording.

The key server configuration for enabling KRaft is `process.roles`.

2023-01-06 18:58 UTC, joel-hamill commented
@addisonhuddy fyi moved this back to "draft" mode to avoid the stale PR reminders.

2026-03-21 17:05 UTC, closed without merging