REP-358 added a demo for Schema translation outside of Confluent Cloud
confluentinc/examples pull request #304
Opened 2019-10-14 15:23 UTC by thomaskwscott

https://confluentinc.atlassian.net/browse/REP-358

This is an example in preparation for a future DOCS ticket that discusses Schema Translation outside Confluent Cloud.

2019-10-15 12:01 UTC, ybyzek requested changes
@thomaskwscott thanks for the PR.  As we discussed offline, let's move the README content to the docs flow, as done similarly for:

- https://github.com/confluentinc/examples/tree/5.3.1-post/ccloud/docs
- https://github.com/confluentinc/examples/tree/5.3.1-post/kubernetes/gke-base/docs
- https://github.com/confluentinc/cp-demo/tree/5.3.1-post/docs

Thanks in advance!

2019-10-15 16:50 UTC, ybyzek requested changes
* Missing `conf.py` (needs to be added into the `docs` folder)
* Update replicator-schema-translation/README: strip out the meat and just add a pointer to the docs landing page

2019-10-15 18:15 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +Confluent Replicator features the ability to translate entries from a source Schema Registry to a destination Schema Registry.
```suggestion
|crep-full| features the ability to translate entries from a source |sr| to a destination |sr|.
```

2019-10-15 18:16 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +This demo provides a docker-compose environment with source and destination Schema Registries in which Schemas will be translated. In this demo we will create an entry in the source Schema Registry a
```suggestion
This demo provides a docker-compose environment with source and destination Schema Registries in which schemas are translated. In this demo, you create an entry in the source |sr| and translate it to the destination.
```

2019-10-15 18:17 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +The scripts directory provides examples of the operations that must be performed to prepare for the translation as well as JSON Replicator configurations required.
```suggestion
The `scripts` directory provides examples of the operations that you must perform to prepare for the translation, as well as JSON Replicator configurations required.
```

2019-10-15 18:17 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +These demos are memory intensive and Docker must be tuned accordingly. In Docker's advanced settings, increase the memory dedicated to Docker to at least 8GB (default is 2GB).
```suggestion
These demos are memory intensive and Docker must be tuned accordingly. In Docker's advanced settings, increase the memory dedicated to Docker to at least 8GB (the default is 2GB).
```

2019-10-15 18:18 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +In addition to Confluent Replicator, the environment contains:
```suggestion
In addition to |crep-full|, the environment contains:
```

2019-10-15 18:18 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +* A single node source cluster containing srcKafka1, in production at least 3 nodes are recommended.
```suggestion
* A single node source cluster containing ``srcKafka1``, in production at least 3 nodes are recommended.
```

2019-10-15 18:19 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +* A single node destination cluster containing destKafka1, in production at least 3 nodes are recommended.
```suggestion
* A single node destination cluster containing ``destKafka1``. In production, at least 3 nodes are recommended.
```

2019-10-15 18:20 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +* A single node Schema Registry cluster containing srcSchemaregistry, in production a master/standby configuration is recommended.
```suggestion
* A single node |sr| cluster containing ``srcSchemaregistry``. In production, a master/standby configuration is recommended.
```

2019-10-15 18:20 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +* A single node Schema Registry cluster containing destSchemaregistry, in production a master/standby configuration is recommended.
```suggestion
* A single node |sr| cluster containing ``destSchemaregistry``. In production, a master/standby configuration is recommended.
```

2019-10-15 18:21 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +* A single Connect worker that will run replicator
```suggestion
* A single |kconnect| worker that runs |crep|.
```

2019-10-15 18:22 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +* A source client container (kafkaClient) that creates a source topic and provides test data
```suggestion
* A source client container (``kafkaClient``) that creates a source topic and provides test data.
```

2019-10-15 18:22 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +1. Creation of a subject in the source Schema Registry
```suggestion
1. Create a subject in the source |sr|.
```

2019-10-15 18:22 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +2. Preparation for Schema translation
```suggestion
2. Prepare for schema translation.
```

2019-10-15 18:23 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +3. Execution of Replicator to perform migration
```suggestion
3. Execute |crep| to perform migration.
```

2019-10-15 18:23 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +4. Post translation Schema registry configuration.
```suggestion
4. Post-translation |sr| configuration. 
```

2019-10-15 18:24 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +  ```
Need to outdent these code blocks.

2019-10-15 18:25 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +Note: the kafkaClient container must complete and exit 0 before verification
```suggestion
.. note:: The ``kafkaClient`` container must complete and ``exit 0`` before verification  
```

2019-10-15 18:25 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +To prepare for Schema translation the source cluster must be put in "READONLY" mode and the destination in "IMPORT" mode.
```suggestion
To prepare for schema translation, you must put the source cluster in "READONLY" mode and the destination cluster in "IMPORT" mode.
```

2019-10-15 18:26 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +  ```
outdent

2019-10-15 18:26 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +Now we submit Replicator to perform the translation.
```suggestion
Submit |crep| to perform the translation.
```

2019-10-15 18:26 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +This should produce:
```suggestion
Your output should resemble:
```

2019-10-15 18:28 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +  ```
```suggestion
.. code:: json
```

2019-10-15 18:28 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +  ```
```suggestion

```

2019-10-15 18:35 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +This should produce:
```suggestion
Your output should resemble:
```

2019-10-15 18:36 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +Note: If replicator is submitted before the Connect worker is ready then the message below will be printed. The script will automatically retry until successful
```suggestion
Note: If replicator is submitted before the Connect worker is ready, the following message is printed. The script automatically retries until successful.
```

2019-10-15 18:37 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +You should see the following:
```suggestion
Your output should resemble:
```

2019-10-15 18:38 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +Note: Replicator may not immediately translate the Schema so this verification should be retired for up to 60 seconds.
```suggestion
Note: Replicator may not translate the schema immediately, so this verification should be retried for up to 60 seconds.
```

2019-10-15 18:38 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +This should produce:
```suggestion
Your output should resemble:
```

2019-10-15 18:39 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +This |crep| demo showcases the transfer of schemas stored in Confluent Schema Registry from one cluster to another.
```suggestion
This |crep| demo showcases the transfer of schemas stored in |sr-long| from one cluster to another.
```

2019-10-15 18:40 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +Confluent Replicator features the ability to translate entries from a source Schema Registry to a destination Schema Registry.
```suggestion
|crep| features the ability to translate entries from a source |sr| to a destination |sr|.
```

2019-10-15 18:41 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +This demo provides a docker-compose environment with source and destination Schema Registries in which Schemas will be translated. In this demo we will create an entry in the source Schema Registry a
```suggestion
This demo provides a docker-compose environment with source and destination registries in which schemas are translated. In this demo, you create an entry in the source |sr| and translate it to the destination.
```

2019-10-15 18:41 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +The scripts directory provides examples of the operations that must be performed to prepare for the translation as well as JSON |crep| configurations required.
```suggestion
The ``scripts`` directory provides examples of the operations that you must perform to prepare for the translation, as well as JSON |crep| configurations required.
```

2019-10-15 18:44 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +-  Confluent Platform |version|
```suggestion
-  |cp| |version|
```

2019-10-15 18:45 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +     $ git clone https://github.com/confluentinc/examples
```suggestion
     git clone https://github.com/confluentinc/examples
```

2019-10-15 18:45 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +     $ cd examples/replicator-schema-translation
```suggestion
     cd examples/replicator-schema-translation
```

2019-10-15 18:45 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +3. Start the entire demo by running a single command. This automatically creates source and destination clusters and adds a Schema to the source cluster Schema Registry. This will take less than 5 mi
```suggestion
3. Start the entire demo by running a single command. This automatically creates source and destination clusters and adds a schema to the source cluster |sr|. This takes less than 5 minutes to complete.
```

2019-10-15 18:45 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +      $ docker-compose up -d
```suggestion
      docker-compose up -d
```

2019-10-15 18:46 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +   Verify the demo has completely started by using Google Chrome to view the Schema Registries, the source cluster is at: http://localhost:8085/subjects (you should see: ``["testTopic-value"]``) and
```suggestion
   Verify the demo has completely started by using Google Chrome to view the Schema Registries. The source cluster is at: ``http://localhost:8085/subjects`` (you should see: ``["testTopic-value"]``) and the destination cluster is at: ``http://localhost:8086/subjects`` (you should see: ``[]``).
```

2019-10-15 18:47 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +4. To prepare for Schema translation the source cluster Schema Registry must be put in "READONLY" mode and the destination in "IMPORT" mode.
```suggestion
4. To prepare for schema translation, you must put the source cluster registry in "READONLY" mode and the destination registry in "IMPORT" mode.
```

2019-10-15 18:47 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +      $ docker-compose exec connect /etc/kafka/scripts/set_sr_modes_pre_translation.sh
```suggestion
      docker-compose exec connect /etc/kafka/scripts/set_sr_modes_pre_translation.sh
```

2019-10-15 18:48 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +   This should produce:
```suggestion
   Your output should resemble:
```

2019-10-15 18:48 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +   .. sourcecode:: bash
```suggestion
   .. sourcecode:: json
```

2019-10-15 18:48 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +      $ docker-compose exec connect /etc/kafka/scripts/submit_replicator.sh
```suggestion
      docker-compose exec connect /etc/kafka/scripts/submit_replicator.sh
```

2019-10-15 18:49 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +5. Now we submit Replicator to perform the translation.
```suggestion
5. Submit |crep| to perform the translation.
```

2019-10-15 18:49 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +   This should produce:
```suggestion
   Your output should resemble:
```

2019-10-15 18:49 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +   .. sourcecode:: bash
```suggestion
   .. sourcecode:: json
```

2019-10-15 18:50 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +6. Now verify the translation by revisiting the Schema Registries at: http://localhost:8085/subjects and: http://localhost:8086/subjects. They should both now list schemas with the destination cluste
```suggestion
6. Now verify the translation by revisiting the registries at: ``http://localhost:8085/subjects`` and ``http://localhost:8086/subjects``. They should both list schemas with the destination cluster showing ``["testTopic.replica-value"]``.
```

2019-10-15 18:51 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +7. To complete the demo return both Schema Registries to ``READWRITE`` mode:
```suggestion
7. To complete the demo return both registries to ``READWRITE`` mode:
```

2019-10-15 18:51 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +      $ docker-compose exec connect /etc/kafka/scripts/set_sr_modes_post_translation.sh
```suggestion
      docker-compose exec connect /etc/kafka/scripts/set_sr_modes_post_translation.sh
```

2019-10-15 18:52 UTC, JimGalasyn commented on replicator-schema-translation/docs/index.rst
> +      $ docker-compose down
```suggestion
      docker-compose down
```

2019-10-15 18:56 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +This demo provides a docker-compose environment with source and destination Schema Registries in which Schemas will be translated. In this demo we will create an entry in the source Schema Registry a
```suggestion
This demo provides a docker-compose environment with source and destination Schema Registries in which schemas are translated. In this demo, you create an entry in the source Schema Registry and translate it to the destination.
```

2019-10-15 18:57 UTC, JimGalasyn commented on replicator-schema-translation/README.md
> +The scripts directory provides examples of the operations that must be performed to prepare for the translation as well as JSON Replicator configurations required.
```suggestion
The `scripts` directory provides examples of the operations that you must perform to prepare for the translation, as well as JSON Replicator configurations required.
```

2019-10-15 18:57 UTC, JimGalasyn approved these changes
LGTM, with some copy edits!

2019-10-16 15:52 UTC, thomaskwscott commented
> * Missing `conf.py` (needs to be added into the `docs` folder)
> * Update replicator-schema-translation/README: strip out the meat and just add a pointer to the docs landing page

conf.py added. Can we leave the Readme until we've sorted where this will go in the docs?

2019-10-16 17:30 UTC, ybyzek commented
> Can we leave the Readme until we've sorted where this will go in the docs?

1. What's required to sort out where this will go in docs?  Can that be done in parallel?
2. Once removing content from the README and merging, there will be just a 20 minute window where it's not available.  IMO that's an acceptable downtime when there are no public docs

2019-10-17 13:50 UTC, thomaskwscott commented
> > Can we leave the Readme until we've sorted where this will go in the docs?
> 
> 1. What's required to sort out where this will go in docs?  Can that be done in parallel?
> 2. Once removing content from the README and merging, there will be just a 20 minute window where it's not available.  IMO that's an acceptable downtime when there are no public docs

Good point, I just had a look and the associated docs ticket is small so we should be able to do these simultaneously. I've changed the readme as requested.

2019-10-17 13:58 UTC, ybyzek approved these changes
Looking so good.  Two more nits but then ship it ;)

2019-10-17 13:58 UTC, ybyzek commented on replicator-schema-translation/README.md
> +You can find the documentation for running this demo at [https://docs.confluent.io/current/tutorials/examples/ccloud/docs/index.html](https://docs.confluent.io/current/tutorials/examples/replicator-s
Is there an error in the link `https://docs.confluent.io/current/tutorials/examples/ccloud/docs/index.html`?

2019-10-17 13:58 UTC, ybyzek commented on replicator-schema-translation/README.md
> +## Prerequisites
For consideration: move Prereqs to the docs (not in the README) to simplify the README

2019-10-17 15:02 UTC, thomaskwscott commented
@ybyzek I fixed the remaining things, but I have no merge perms. Can you merge for me?

2019-10-17 15:22 UTC, merged