DEVX-1662: Update clickstream to sessionize data
confluentinc/examples pull request #547
Opened 2020-04-07 22:28 UTC by bbejeck

2020-04-08 01:23 UTC, ybyzek requested changes
Great PR @bbejeck .

Additional comments:

1. Please update the image https://github.com/confluentinc/examples/blob/5.5.x/clickstream/images/clickstream-dashboard.png

2. The docs page (source: https://github.com/confluentinc/examples/blob/5.5.x/clickstream/docs/index.rst ... rendered: https://docs.confluent.io/current/ksql/docs/tutorials/clickstream-docker.html) has users walk through the demo one step at a time, users don't have to run the start.sh script.  So the part that does the pause/resume should be (a) extracted into a separate script and let users run the separate script or (b) explained how to run manually by users in the docs.  Either way, a docs update is warranted.

3. Can you add a comment into the script itself to explain the purpose of toggling the connector?

2020-04-08 01:23 UTC, ybyzek commented on clickstream/start.sh
> + echo -e "\nPaused the clickstream generate for 35 seconds\n"
```suggestion
 echo -e "\nPaused the clickstream datagen for 35 seconds\n"
```

2020-04-08 01:23 UTC, ybyzek commented on clickstream/start.sh
> + echo -e "\Resumed the clickstream generate for 90 seconds. Then the cycle will repeat\n"
```suggestion
 echo -e "\Resumed the clickstream datagen for 90 seconds. Then the cycle will repeat\n"
```

2020-04-08 17:24 UTC, bbejeck commented
@ybyzek 
For #1 the clickstream image has been updated with this PR
https://github.com/confluentinc/examples/blob/DEVX-1662_update_clickstream_to_sessionize_data/clickstream/images/clickstream-dashboard.png.  I guess Github only shows the diff In size for binary files and you can't view them.

Ack on #2 and #3 from comments.

2020-04-08 20:27 UTC, bbejeck commented
@ybyzek comments addressed

2020-04-08 20:42 UTC, ybyzek reviewed
This looks really good @bbejeck, excellent description.

I noticed two other things that we should probably fix (and feel free to assign this to me if you prefer I touch this up):

1. Sequencing in the docs/index.rst -- the screenshot `docs/images/grafana-success.png` comes BEFORE the section on sessionizing the data.  The "success" screenshot should come after the data starts getting sessionized.

2. `images/clickstream-dashboard.png` is an unnecessary duplicate of `docs/images/grafana-success.png`.  Perhaps we should do:

```
cp images/clickstream-dashboard.png docs/images/grafana-success.png
rm -fr images
... # and then replace wherever images/clickstream-dashboard.png is referenced (which is nowhere?)
```

2020-04-08 20:42 UTC, ybyzek commented on clickstream/sessionize-data.sh
> +echo "Starting to run the session data, I'll pause for 90 seconds to allow more data to generate"
```suggestion
echo "Running for 90 seconds to allow clickstream data to generate"
```

2020-04-08 20:42 UTC, ybyzek commented on clickstream/sessionize-data.sh
> + echo "Paused the clickstream datagen for 35 seconds"
```suggestion
 echo "Pausing the clickstream datagen for 35 seconds"
```

2020-04-08 20:42 UTC, ybyzek commented on clickstream/sessionize-data.sh
> + echo "Resumed the clickstream datagen for 90 seconds. Then the cycle will repeat"
```suggestion
 echo "Resuming the clickstream datagen for 90 seconds. Then the cycle will repeat"
```

2020-04-08 22:15 UTC, bbejeck commented
Thanks for the review @ybyzek.

>Sequencing in the docs/index.rst -- the screenshot docs/images/grafana-success.png comes BEFORE the section on sessionizing the data. The "success" screenshot should come after the data starts getting sessionized.

I had questions myself about the order of things.  In this update, I added the `sessionizing` section entirely before the `grafana` section.  I think this should be ok, but let me know if want something more along the lines of

1. Instructions for Grafana
2. Instructions for session data
3. Then show link to grafana success.

2020-04-09 13:48 UTC, bbejeck commented
I remembered the sessionizing is a blocking script so I updated to the `index.rst` page to have the following order:

1. Instructions for Grafana
2. Instructions for session data
3. Then show grafana success image.

2020-04-09 17:10 UTC, ybyzek approved these changes
@bbejeck very nice work!  LGTM

2020-04-09 17:55 UTC, merged

2020-04-09 17:55 UTC, bbejeck commented
merged #547 into 5.5.x

2020-04-09 17:56 UTC, bbejeck commented
merged into master with pint