DEVX-1881: microservices-orders: Prepares for usage of latest kafka-s…
confluentinc/examples pull request #690
Opened 2020-06-30 04:17 UTC by rspurgeon

…treams-examples

Right now this will require running w/ a new variable to test with
a branch of kafka-streams-examples not yet merged.  For example:

KAFKA_STREAMS_BRANCH=DEVX-1881 ./start.sh

However, running the docker version is not yet possible until we publish
a version of the docker image, or the streams team releases a version
with the changes in PR #346

2020-06-30 13:27 UTC, ybyzek commented
@rspurgeon 

1. We should not merge without a Docker-ready version of this demo.  From 5.5.1-post to 5.5.2 is GA, we need an interim solution (we publish the image or demo builds the image).  After 5.5.2 is GA, the official kafka-streams-examples Docker image should be fine.
2. Now that 5.5.1-post is GA, let's retarget both PRs to 5.5.1-post instead of 5.5.0-post.

2020-06-30 14:17 UTC, rspurgeon commented
> @rspurgeon
> 
>     1. We should not merge without a Docker-ready version of this demo.  From 5.5.1-post to 5.5.2 is GA, we need an interim solution (we publish the image or demo builds the image).  After 5.5.2 is GA, the official kafka-streams-examples Docker image should be fine.
> 
>     2. Now that 5.5.1-post is GA, let's retarget both PRs to 5.5.1-post instead of 5.5.0-post.
> 
>     3. How do I run this against CCloud?

@ybyzek 
1. I'm aware of the need for Docker, I mentioned this in the PR description.  I'm investigating a solution now.  I will not merge until that's complete, but Draft PRs are often ignored so I moved it to a Full PR.
2. Ok
3. This PR does not create a ccloud version of the demo, it's only to adopt these demos to changes in the dependent microservices code.  I've successfully ran the microservices code against ccloud (which was my goal for DEVX-1881) but an automated and documented version of this is not part of this PR.

2020-06-30 15:50 UTC, rspurgeon commented
@ybyzek please see ammended 'tips' on validating microservices code changes against ccloud cluster and SR

2020-07-02 18:07 UTC, rspurgeon commented
Docker demo now works w/ a manually built version of the kafka-streams-image docker image (see PR description)

2020-07-07 16:21 UTC, ybyzek commented on microservices-orders/.gitignore
> +*.log
Unnecessary with the other `.gitignore`?

2020-07-07 16:23 UTC, ybyzek approved these changes
LGTM!  (Also approved https://github.com/confluentinc/kafka-streams-examples/pull/346)

2020-07-08 13:35 UTC, ybyzek requested changes
@rspurgeon just realized that all the files in https://github.com/confluentinc/examples/tree/5.5.1-post/microservices-orders/exercises also need to be updated to reflect the changes in https://github.com/confluentinc/kafka-streams-examples/pull/346/files

2020-07-08 13:38 UTC, rspurgeon commented
> @rspurgeon just realized that all the files in https://github.com/confluentinc/examples/tree/5.5.1-post/microservices-orders/exercises also need to updated to reflect the changes in https://github.com/confluentinc/kafka-streams-examples/pull/346/files

Thank you, will address

2020-07-08 15:41 UTC, rspurgeon commented
@ybyzek updated the excercises code.  I don't believe that any docs changes are required but please double check me on that.  Thanks for catching this miss

2020-08-06 13:47 UTC, ybyzek commented
@rspurgeon what's the status of this PR?  Can it be closed?

2020-08-06 14:02 UTC, rspurgeon commented
@ybyzek I'm going to close this, the changes made it in https://github.com/confluentinc/examples/pull/702

2020-08-06 14:02 UTC, closed without merging