Added hocon template
confluentinc/examples pull request #966
Opened 2021-03-23 04:32 UTC by gAmUssA

### Description 

_What behavior does this PR change, and why?_

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

2021-03-23 11:25 UTC, ybyzek requested changes
All the other files in this directory have a `.config` extension, can you please rename these 2 files to have the same extension, for consistency?

2021-03-23 14:19 UTC, laura-brouckman commented on clients/docs/includes/configs/cloud/hocon-sr.conf
> +    //# Required connection configs for Confluent Cloud Schema Registry
should this just be # (remove the //)?

2021-03-23 14:19 UTC, laura-brouckman approved these changes
lgtm after Yeva's comment

2021-03-23 19:04 UTC, gAmUssA commented on clients/docs/includes/configs/cloud/hocon-sr.conf
> +    //# Required connection configs for Confluent Cloud Schema Registry
fixed @laura-brouckman

2021-03-23 19:05 UTC, gAmUssA commented
> All the other files in this directory have a `.config` extension, can you please rename these 2 files to have the same extension, for consistency?

in general, I don't have a strong opinion on this but in ktor they use `application.conf` and my module follows same pattern for configuration - `kafka.conf`. Let me know if it's a showstopper @ybyzek

2021-03-23 19:11 UTC, ybyzek commented
@gAmUssA maybe not a showstopper, but a quick clarification question: how/where will these be used, where will they be surfaced?  Answer will help determine if consistency is super important or maybe not.

2021-03-23 19:20 UTC, gAmUssA commented
> @gAmUssA maybe not a showstopper, but a quick clarification question: how/where will these be used, where will they be surfaced? 

Firstly, copy from cloud UI, paste into IDE.
I want to add this to `ccloud-stack` as well (but later)

2021-03-23 19:24 UTC, ybyzek commented
@gAmUssA If you want this picked up by CCloud UI, then engineering needs to be a part of this as well (cc: @laura-brouckman) and for that reason, I think consistency is important and my vote would be to rename the files.  FWIW I often see `conf`, `config`, and `cfg` interchanged, so hopefully it's ok.

2021-03-23 19:36 UTC, gAmUssA commented
@ybyzek a standard behaviour of the library described here https://github.com/lightbend/config#standard-behavior
They don't use `cfg` convention.

2021-03-24 23:02 UTC, gAmUssA commented
@laura-brouckman @ybyzek do we still have any concerns?

2021-03-24 23:10 UTC, ybyzek commented
> @gAmUssA If you want this picked up by CCloud UI, then engineering needs to be a part of this as well (cc: @laura-brouckman) and for that reason, I think consistency is important and my vote would be to rename the files. 

Yes, please rename to `.config` for consistency

2021-03-25 02:17 UTC, gAmUssA commented
> Yes, please rename to `.config` for consistency

@ybyzek ✅ done

2021-03-25 12:34 UTC, ybyzek approved these changes
LGTM! 👍

2021-03-25 12:34 UTC, merged